name: ci-test

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: Boot the docker containers with latest guacamole
      working-directory: ./devel-utils
      run: docker compose up -d

    - name: Install latest ansible and make the collection available
      run: |
        mkdir -p ~/.ansible/collections/ansible_collections/scicore/
        ln -s ${GITHUB_WORKSPACE} ~/.ansible/collections/ansible_collections/scicore/guacamole
        pip install ansible

    - name: Execute the CI playbook
      working-directory: ./devel-utils
      run: ansible-playbook test-collection.yml
